**Practicee - DAY 3**

In [6]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [7]:
#Code here
array=np.arange(0,11)
print(array)
array[4]=1
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  1  5  6  7  8  9 10]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [8]:
#Code here
a,b=map(int ,input("Enter a,b two Numbers").split(",") )
print(a,b)
A=np.random.randint(0,100,size=(a,b)) 
print(A)
print("\n Mean of Array ",A.mean())


5 6
[[56 92 87 46 58  8]
 [46 53 71 88 42 67]
 [88 49 99 48 59 49]
 [42 96 13 63 19 39]
 [65 54 80  2 22 49]]

 Mean of Array  55.0


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [9]:
#Code here
def funct(a,b):
    arr=np.ones((a,b))
    arr[1:-1,1:-1]=0
    return arr
    

"""
np.random.seed(0)
c=np.random.randint(1,11,size=(4,4))

print(c)
# top row
print(c[0,:])

# left column
print(c[:,0])

#right column
print(c[:,-1])

#bottom Row
print(c[-1,:])

# inner Elements
print(c[1:-1,1:-1])

"""
a,b=map(int ,input("Enter a,b two Numbers").split(",") )
print(a,b)
arr=funct(a,b)
print(arr)


5 6
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [10]:
#Code here
print(np.random.rand(10)) # This gives random values in [0.0, 1.0) — 0 is possible, 1 is excluded.
#So, 0 can occur, which violates the "exclude 0" rule.

print(np.random.uniform(low=1e-10,high=1-1e-10 ,size=10))
## low=1e-10 → very close to 0, but not 0.
# high=1 - 1e-10 → very close to 1, but not 1.
# This guarantees (0, 1) — both endpoints excluded.



[0.56992044 0.62923457 0.99610408 0.81525774 0.93404319 0.226106
 0.32890765 0.73250872 0.79497417 0.84577265]
[8.11702875e-02 2.24275434e-02 2.94008432e-01 3.32402410e-04
 5.75470836e-01 1.88914183e-02 6.30421934e-01 2.02856070e-01
 3.25989523e-01 7.99560314e-02]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [11]:
#Code here
print(np.eye(3,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [12]:
#Code here
print(np.random.randint(0,4,size=(5,5)))

[[2 1 0 0 1]
 [3 0 1 3 2]
 [1 2 0 1 1]
 [0 3 3 2 3]
 [1 1 0 1 2]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [13]:
#code here
arr=np.random.randint(1,101,size=(10,2))
print(arr)

point = np.array([2,3])
print(point)

[[83 86]
 [92 12]
 [62 73]
 [44 38]
 [45 84]
 [63 69]
 [32 55]
 [46 20]
 [87 64]
 [35 40]]
[2 3]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [14]:
#Code here
x=np.random.randint(1,10,size=(6,7,8))
print(x)

hundred_index=np.unravel_index(99,x.shape)
print(hundred_index)
print("Element at Hundred position",x[hundred_index])

[[[5 2 2 9 8 6 8 3]
  [4 7 7 4 7 4 3 7]
  [1 1 2 3 1 8 1 5]
  [6 6 3 6 9 9 4 5]
  [4 5 3 8 9 1 9 9]
  [5 3 4 7 7 7 2 6]
  [8 6 3 7 4 2 3 3]]

 [[8 1 4 3 9 6 9 3]
  [4 9 2 6 3 1 4 7]
  [4 1 3 5 4 2 8 1]
  [2 3 1 1 1 9 8 2]
  [6 1 6 3 2 9 9 6]
  [1 3 4 3 3 9 4 6]
  [3 9 5 8 5 1 1 1]]

 [[6 7 8 7 6 5 9 7]
  [9 3 8 2 2 3 7 8]
  [3 4 1 8 5 7 4 2]
  [9 2 9 1 6 6 2 3]
  [2 4 9 1 4 8 6 2]
  [1 3 5 3 5 4 4 6]
  [2 3 4 3 4 2 1 9]]

 [[4 8 4 9 6 9 4 3]
  [9 7 2 9 4 3 2 4]
  [4 4 5 3 9 3 7 9]
  [2 2 5 5 3 3 4 3]
  [9 8 4 3 3 6 3 2]
  [9 8 4 9 9 3 4 4]
  [2 4 2 2 2 9 5 8]]

 [[7 6 1 9 6 8 1 1]
  [3 4 6 3 1 9 1 9]
  [3 1 5 8 3 7 8 8]
  [3 2 2 6 7 7 5 4]
  [2 5 1 3 9 7 3 6]
  [8 4 3 3 4 8 9 7]
  [4 2 5 8 6 7 7 9]]

 [[5 5 1 2 7 3 6 1]
  [2 9 8 4 2 4 6 4]
  [5 9 5 2 8 2 6 9]
  [6 5 8 5 4 9 3 6]
  [2 2 6 8 6 5 3 5]
  [6 3 5 8 9 7 7 3]
  [8 6 6 3 1 3 2 3]]]
(np.int64(1), np.int64(5), np.int64(3))
Element at Hundred position 3


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [15]:
#Code here
input_list=list(map(int,(input("Enter the Space Separated List")).split()))
print("Input list :",input_list)

Numpy_array=np.array(input_list)
print("Numpy Array :",Numpy_array)

#slicing 
Reverse=Numpy_array[::-1]
print("Reverse Numpy Array",Reverse)

#flipping
Revers=np.flip(Numpy_array)
print("Reverse Numpy Array",Revers)

Input list : [1, 2, 3, 4, -8, -10]
Numpy Array : [  1   2   3   4  -8 -10]
Reverse Numpy Array [-10  -8   4   3   2   1]
Reverse Numpy Array [-10  -8   4   3   2   1]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [32]:
#Code here
def Count_Elements(Numpy_array):
    return Numpy_array.size

print("elements_count ",Count_Elements(np.array([])))
print("elements_count ",Count_Elements(np.array([1, 2])))
print("elements_count ",Count_Elements(np.random.randint(1,10,size=(1,5,6,))))

print(type(np.array([])))

elements_count  0
elements_count  2
elements_count  30
<class 'numpy.ndarray'>


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [17]:
"""Theroy :
The softmax function is used in machine learning and deep learning, especially in classification problems (like image or text classification).

It turns a list of raw numbers (called logits or scores) into probabilities — numbers between 0 and 1 that add up to 1.



"""

'Theroy :\nThe softmax function is used in machine learning and deep learning, especially in classification problems (like image or text classification).\n\nIt turns a list of raw numbers (called logits or scores) into probabilities — numbers between 0 and 1 that add up to 1.\n\n\n\n'

In [34]:
#Code here
def Softmax(numpy_array):
    # there may Overflow if number inside the Numpy array array is very large like >10000 so exp(10000)-> infinite so to overcome this situation
    # we can substract the maximum number from whole array so that we get the smalledformat array and then apply the expo to it
    smallerformat=numpy_array - np.max(numpy_array)
    Exponent=np.exp(smallerformat)
    sum=np.sum(Exponent)
    Solution=Exponent /sum
    return Solution

NumpyArray=np.array( [86.03331084 ,37.7285648 ,48.64908087 ,87.16563062 ,38.40852563 ,37.20006318])
print(Softmax(NumpyArray))

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


In [35]:

NumpyArray=np.array( [33.17344305 ,45.61961654, 82.05405781 ,80.9647098 , 68.82830233 ,91.52064278])
print(Softmax(NumpyArray))

[4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [45]:
#Code here

def VerticalStack(*args):
    return np.vstack(args)

a= np.array([[0,1,2,3,4],
             [1,1,1,1,1]])

b= np.array([[1,1,1,1,1],
      [1,1,1,1,1]])
Vertical=VerticalStack(a,b)
print(Vertical)
        
c=np.array( [[0.10117373 ,0.1677244 , 0.73764059, 0.83166097, 0.48985695],
 [0.44581567 ,0.13502419, 0.55692335, 0.16479622, 0.61193593]]) 

Vertical=VerticalStack(a,b,c) 
print(Vertical)

[[0 1 2 3 4]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0.         1.         2.         3.         4.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here
import datetime
def date_array(start,end):
    if not isinstance(start,str) or not isinstance(end,str):
        raise ValueError("Enter the Date Correctly")
    # date is in format DD-MM-YY
    format="%Y-%m-%d"
    # creating the date object from the string 
    obj1=datetime.datetime.strptime(start,format)
    obj2=datetime.datetime.strptime(end,format)
    difference=obj2-obj1
    Days=difference.days+1 # for end date we add +1 to it 
    Date_list=[(obj1 + datetime.timedelta(days=i)).strftime(format) for i in range(Days) ]
    return Date_list

# Example 1
Dates=date_array(start = '2020-09-15', end = '2020-09-25')
print(Dates)


['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18', '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22', '2020-09-23', '2020-09-24', '2020-09-25']


In [56]:
# Example 2:
Dates=date_array(start = '2022-12-01', end = '2022-12-06')
print(Dates)

['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']


In [55]:
# Example 3:
Dates=date_array(start = '2020-11-25', end = '2020-11-30')
print(Dates)


['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28', '2020-11-29', '2020-11-30']


In [57]:
Dates=date_array(start = '2011-11-24', end = '2018-11-30')
print(Dates)


['2011-11-24', '2011-11-25', '2011-11-26', '2011-11-27', '2011-11-28', '2011-11-29', '2011-11-30', '2011-12-01', '2011-12-02', '2011-12-03', '2011-12-04', '2011-12-05', '2011-12-06', '2011-12-07', '2011-12-08', '2011-12-09', '2011-12-10', '2011-12-11', '2011-12-12', '2011-12-13', '2011-12-14', '2011-12-15', '2011-12-16', '2011-12-17', '2011-12-18', '2011-12-19', '2011-12-20', '2011-12-21', '2011-12-22', '2011-12-23', '2011-12-24', '2011-12-25', '2011-12-26', '2011-12-27', '2011-12-28', '2011-12-29', '2011-12-30', '2011-12-31', '2012-01-01', '2012-01-02', '2012-01-03', '2012-01-04', '2012-01-05', '2012-01-06', '2012-01-07', '2012-01-08', '2012-01-09', '2012-01-10', '2012-01-11', '2012-01-12', '2012-01-13', '2012-01-14', '2012-01-15', '2012-01-16', '2012-01-17', '2012-01-18', '2012-01-19', '2012-01-20', '2012-01-21', '2012-01-22', '2012-01-23', '2012-01-24', '2012-01-25', '2012-01-26', '2012-01-27', '2012-01-28', '2012-01-29', '2012-01-30', '2012-01-31', '2012-02-01', '2012-02-02', '2012

###`Q-14:` Subtract the mean of each row from a matrix.

In [109]:
#code here
np.random.seed(8)
Array=np.random.randint(1,10,size=(3,3))
print(Array)
mean=np.mean(Array,axis=1,keepdims=True).astype(int)
print("Mean =",mean)
print(Array-mean)

[[4 5 2]
 [6 9 4]
 [9 1 6]]
Mean = [[3]
 [6]
 [5]]
[[ 1  2 -1]
 [ 0  3 -2]
 [ 4 -4  1]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [110]:
#Code here
np.random.seed(8)
Array=np.random.randint(1,10,size=(3,3))
print(Array)

[[4 5 2]
 [6 9 4]
 [9 1 6]]


In [113]:
Array[:,0] =Array[:,0]-Array[:,1] 
print(Array)

[[-1  5  2]
 [-3  9  4]
 [ 8  1  6]]


###`Q-16:` Replace odd elements in arrays with -1.

In [120]:
#Code here
np.random.seed(8)
Array=np.random.randint(1,10,size=(3,3))
print(Array)

[[4 5 2]
 [6 9 4]
 [9 1 6]]


In [121]:
# we get boolean format Numpy Array : True Where the Elements are Odd and False Where the ELements are Even
Boolean_format=Array%2!=0
print(Boolean_format)
print(type(Boolean_format))


# Boolean Indexing : PRovide only the True Elements to us
NewArray=Array[Boolean_format]
print("Odd Numberes",NewArray)

# question Solution:
Array[Boolean_format]=-1
print(Array)


[[False  True False]
 [False  True False]
 [ True  True False]]
<class 'numpy.ndarray'>
Odd Numberes [5 9 9 1]
[[ 4 -1  2]
 [ 6 -1  4]
 [-1 -1  6]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [132]:
#Code here
"""
np.maximum(array1, array2) compares element by element.

Returns a new array where each element is the maximum of the two at that position.
"""
def Max(Array1,Array2):
    if Array1.shape !=Array2.shape:
        raise ValueError("Enter ")
    return np.maximum(Array1,Array2)
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
max=Max(a,b)
print(max)


[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Theory :
"""Normalization transforms data to a common scale (often between 0 and 1).
 This makes comparison easier and removes units or differences in scales.

 Explanation of the terms:
X: the original array (or an individual element of it)

X_min: the minimum value in the array

X_max: the maximum value in the array

X_normalized: the normalized result, which lies between 0 and 1
"""

In [135]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[1966, 3223, 2765, 7510,  562],
       [5790,  798, 3496, 1305, 7010],
       [4897, 3536, 8150, 8835, 6088],
       [9224, 9416, 2059, 5745, 4900],
       [3344, 8117, 3922, 3399, 2868],
       [2452, 8445, 9541, 4855, 2857],
       [6592, 1146, 5238,  124, 6705],
       [6507, 9830, 4475, 1310, 8139]], dtype=int32)

In [138]:
#Code here
#1 :Fetch Every Alternate Column of Array
def Alternate(array):
    # Alternate
    print(array[:,::2])

Alternate(arr1)


[[1966 2765  562]
 [5790 3496 7010]
 [4897 8150 6088]
 [9224 2059 4900]
 [3344 3922 2868]
 [2452 9541 2857]
 [6592 5238 6705]
 [6507 4475 8139]]


In [143]:
#2 :Normalize the Given Array

def Normalize(array):
    Min=array.min()
    Max=array.max()
    if Min==Max:
        return ValueError("Max != Min (max Cannot be same as min) ")
    Normalize=(array-Min)/(Max-Min)
    return Normalize

print(Normalize(arr1))


[[0.18977952 0.31928704 0.27209973 0.76097259 0.04512673]
 [0.58376262 0.06944158 0.34741397 0.12167731 0.70945807]
 [0.49175768 0.35153513 0.82691119 0.89748609 0.61446528]
 [0.93756439 0.95734597 0.19936122 0.57912631 0.49206676]
 [0.33175355 0.82351123 0.39130435 0.33742015 0.28271172]
 [0.23985164 0.85730476 0.9702246  0.48743046 0.28157841]
 [0.66639192 0.10529569 0.52689058 0.         0.67803421]
 [0.65763445 1.         0.44827941 0.12219246 0.82577787]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
#Code here
"""
We can remove a single element from a NumPy array

np.delete(arr, index) 

arr: the original array
index: the index of the element to remove"""
# it does not change the original array ,it gives the copy of the array
# so to change assign it back to original array
"""
To Get the maximum element Index IN Numpy Element
np.argmax(arr) → gives the index of the first occurrence of the maximum value.
"""
def NthLargest(array,n):

    if n==1:
       return np.max(array)
    else:
        for i in range(1,n):
          array=np.delete(array,np.argmax(array))
        return np.max(array)
  

12


In [158]:
#testing
arr=np.array([12,34,40,7,1,0]) 
print(NthLargest(arr,3))

#testing
arr=np.array([12,34,40,7,1,0]) 
print(NthLargest(arr,1))

#testing
arr=np.array([12,34,40,7,1,0]) 
print(NthLargest(arr,5))


12
40
1


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
"""NumPy  has np.append() —That can add the ELements in numpy even if you already created it 

Syntax np.append(Array_name,element_to_Append)"""

In [167]:
#code here
def Encoding(array):
    size=array.size
    encoded=np.array([])
    for j in range(size):
        for _ in range(size):
            encoded=np.append(encoded,array[j])
    
    for _ in range(size):
        encoded=np.append(encoded,array)
    return encoded
    


a = np.array([1,2,3])
a.size
Encoded_Array=Encoding(a)
print(Encoded_Array)
print(type(Encoded_Array))

[1. 1. 1. 2. 2. 2. 3. 3. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3.]
<class 'numpy.ndarray'>


In [168]:
# Theory for more better way :
"""
np.repeat(array, 3)	Repeats each element of array three times
np.tile(array, 3)	Repeats the whole array array three times
np.concatenate([A1,A2])	Joins both arrays into one
"""

def Encoding(array):
    Part1=np.repeat(array,3)

    part2=np.tile(array,2)

    Result=np.concatenate([Part1,part2])
    

    return Result


a = np.array([1,2,3])
a.size
Encoded_Array=Encoding(a)
print(Encoded_Array)
print(type(Encoded_Array))


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3]
<class 'numpy.ndarray'>


[Day 4](NumpyDay4.ipynb)