__DAY 2__

### Basic Operations On Numpy_Array

In [2]:
import numpy as np

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# scalar Operations:A scalar is just a single number (like 5). 
# When We perform operations between a NumPy array and a scalar, NumPy broadcasts the scalar to all elements.
print(x + 5)        # [6 7 8]
print(x-5)          # [-4 -3 -2]
print(x*5)          # [ 5 10 15]
print(x/5)          # [0.2 0.4 0.6]

# Relation Operations: x>1
# Compares each element of x with 1.
# Returns a Boolean array:
"""
1 > 1 → False

2 > 1 → True

3 > 1 → True"""
print(x>1)           #[False  True  True]

# vector Operations:These are operations between two arrays of the same shape (x and y). Each element from x is combined with the corresponding element in y.

print(x+y)           #[5 7 9]
print(x-y)            #[-3 -3 -3]
print(x*y)           #[ 4 10 18]
print(x/y)            #[0.25 0.4  0.5 ]

[6 7 8]
[-4 -3 -2]
[ 5 10 15]
[0.2 0.4 0.6]
[False  True  True]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# another Example
x = np.arange(12).reshape(3,4)
y = np.arange(12,24).reshape(3,4)
print(x,"\n\n",y)

# Scalar Operations   
print(x + 2)
print(x - 2 )   
print(x ** 2)      
print(x / 2)     


#Vector Operations
print(x + y)       
print(x * y) 
 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[False False False False]
 [False False False False]
 [False False False False]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


# Array Function

In [20]:
# Array Functions
A=np.random.random((3,3))
A=np.round(A*100)
print(A)

[[93. 86. 39.]
 [83. 74.  6.]
 [45. 70. 71.]]


In [22]:
# max/min/sum/prod

#1. max
max=np.max(A)
print(max)

#2 min
min=np.min(A)
print(min)

#3 sum
sum=np.sum(A)
print(sum)

#4 prod
product=np.prod(A)
print(product)

93.0
6.0
567.0
2570845465515600.0


In [33]:
# In specific Colums or rows 
# use axis=0 for colums and axis=1 for rows
print(f"\n Array ::\n{A}\n")
max=np.max(A,axis=0)
print("Columns Maximum",max)
max=np.max(A,axis=1)
print("Row Maximum",max)

Min=np.min(A,axis=0)
print("\nColumns Minimum",Min)
Min=np.min(A,axis=1)
print("Row Minimum",Min)


prod=np.prod(A,axis=0)
print("\nColumns product",prod)
prod=np.prod(A,axis=1)
print("Row product",prod)

sum=np.sum(A,axis=0)
print("\nColumns sum",sum)
sum=np.sum(A,axis=1)
print("Row sum",sum)



 Array ::
[[93. 86. 39.]
 [83. 74.  6.]
 [45. 70. 71.]]

Columns Maximum [93. 86. 71.]
Row Maximum [93. 83. 71.]

Columns Minimum [45. 70.  6.]
Row Minimum [39.  6. 45.]

Columns product [347355. 445480.  16614.]
Row product [311922.  36852. 223650.]

Columns sum [221. 230. 116.]
Row sum [218. 163. 186.]


In [35]:
# Statistics Related Computations
"""NumPy allows fast computation of common statistics useful in data science and machine learning."""

data = np.array([12, 15, 20, 22, 24, 30])
print(data)
print("Mean:", np.mean(data))          # 20.5
print("Median:", np.median(data))      # 21.0
print("Standard Deviation:", np.std(data))  # ~5.9
print("Variance:", np.var(data))       # ~34.8

[12 15 20 22 24 30]
Mean: 20.5
Median: 21.0
Standard Deviation: 5.880759588125784
Variance: 34.583333333333336


In [37]:
# Universal Functions
"""ufuncs (universal functions) operate element-wise and are optimized in C, making them super fast."""

a = np.random.rand(2,2)
print(a)
print(np.sqrt(a)) # square Root of all elements    
print(np.exp(a))  # Exponent of all Elements
print(np.log(a))  # Log of all Elements 
print(np.round(a))   #Rounds to the nearest integer (or to a specified number of decimal places).
print(np.floor(a))    #np.floor() – Round down(Rounds down to the nearest whole number (towards negative infinity).)
print(np.ceil(a))    #np.ceil() – Round up(Rounds up to the nearest whole number (towards positive infinity).)

[[0.12321394 0.87764278]
 [0.43000314 0.54295568]]
[[0.35101843 0.93682591]
 [0.65574625 0.73685526]]
[[1.13112638 2.40522338]
 [1.53726235 1.72108632]]
[[-2.09383312 -0.13051563]
 [-0.84396276 -0.61072759]]
[[0. 1.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [ ]:
# .dot product of matrix
A1=np.arange(0,12).reshape(4,3)
A2=np.arange(12,24).reshape(3,4)
print(A1,'\n\n',A2)
np.dot(A1,A2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 56,  59,  62,  65],
       [200, 212, 224, 236],
       [344, 365, 386, 407],
       [488, 518, 548, 578]])

In [154]:
# Random Functions: Provides tools for random number generation, simulations, and probabilistic tasks.

# Uniform Distribution [0.0,1.0)
# 1. np.random.random(size=(n,m)):
"""Returns a n*m NumPy array filled with random float values 
between 0.0 and 1.0 (uniform distribution)[0.0, 1.0)..
it takes a tuple for shape."""
A=np.random.random(size=(4,4))
np.random.random((4,4)) # both can work but requires always tuple: (n,m)
print(A)


#2 .np.random.rand(n,m)
"""Returns a n*m NumPy array filled with random float values 
between 0.0 and 1.0 (uniform distribution).
it takes a two values  for shape.
size =(n,m) not work here"""
B=np.random.rand(4,4)
print(B)



# normal Distribution(Gaussian) (-∞, ∞)
#3 .np.random.randn(n)
"""
Generates random floats from a standard normal distribution(-∞, ∞)
(mean = 0, standard deviation = 1).

This is useful when simulating data that follows a bell curve (Gaussian distribution).
it takes a two values for shape"""

C=np.random.randn(4,4)
print(C)


#Discrete uniform  : [low, high)
# 4. .np.random.randint(low,high,size=(n,m))
D=np.random.randint(0,100,size=(4,4))
print(D)



# 5. np.random.choice(array, size, replace=True, p=probabilities)
"""Selects random elements from a 1D array or list.
replace=True: sampling with replacement
p: probabilities for each element (optional)"""

E = [10, 20, 30, 40]
F=np.random.choice(E, size=(4,4))
print(F)



# 6. np.random.shuffle(array)
"""Randomly shuffles the elements of an array in-place (only along the first axis)."""
E = [10, 20, 30, 40]
G=np.random.shuffle(E)
print(E)




[[0.20915703 0.28691504 0.67726331 0.06303829]
 [0.55564924 0.00924007 0.8330381  0.98432943]
 [0.70349478 0.1816312  0.51239346 0.58044714]
 [0.78754216 0.60647546 0.21840285 0.45516882]]
[[0.41049214 0.42822383 0.29784182 0.40113234]
 [0.12065699 0.98069967 0.40612049 0.56921076]
 [0.3436055  0.78887278 0.41137241 0.35927142]
 [0.39949891 0.30183088 0.77521978 0.92621293]]
[[ 0.3212809  -0.12393044  0.02212126 -0.32128651]
 [ 0.69261805 -0.35352352  0.81228996 -1.14178779]
 [-0.28754879  1.31554171  0.68578051  0.52459879]
 [-0.7933874  -0.23788075  0.56949752 -1.51060714]]
[[51 73 53 69]
 [33  7 94 72]
 [84  7 67 85]
 [91 67 84 71]]
[[40 40 10 20]
 [40 40 30 20]
 [40 40 20 20]
 [10 10 40 30]]
[30, 20, 40, 10]


In [198]:

# 7. np.random.seed(number)
"""sets the starting point (called a seed) for NumPps random number generator.
Because by default, random numbers change every time you run your script.
But if you use np.random.seed(0),  so you'll get the same output every time.
Change the seed → change the output (but still fixed) for next run 
"""
np.random.seed(0)
print(np.random.rand(3))
# Will always return the same 3 numbers every run


np.random.randint(0,100,size=(4,4))


[0.5488135  0.71518937 0.60276338]


array([[67,  9, 83, 21],
       [36, 87, 70, 88],
       [88, 12, 58, 65],
       [39, 87, 46, 88]], dtype=int32)

__Simple Task to perfomr ::__ 

1.Create a 4×4 matrix of random integers from 0 to 100.

2/Find the sum, mean and std of each column.

3.Use np.sqrt() on only even numbers in an array.

In [12]:
import numpy as np
#1 Crete the 4*4 array with (0-100 )Elements
myArray=np.random.randint(0,101,size=(4,4))
print("Random Array from 0,100\n",myArray)

#2 axis=0 for colums
sum=np.sum(myArray,axis=0)
mean=np.mean(myArray,axis=0)
standard_deviation=np.std(myArray,axis=0)
print("Sum :",sum,"\nMean :",mean,"\nStandard Deviation: ",standard_deviation)

#3 : Sqrt() the Even Elements LeaveOther Elements as they are
# creating the Bool Matrix with using the COndition
Even_Bool=myArray%2==0
print(Even_Bool)
# create the Copy of the array to not change the original array
copyarray=myArray.copy()
# Using Boolean Indexing, it only gives tthe True Values and apply the Operation on it 
# copyarray[Even_bool] =>> this line give the only those elements of Numpy array that are true in bool format
copyarray[Even_Bool]=np.sqrt(copyarray[Even_Bool])
print("New Array With Square Root of only Even Elements :\n",copyarray)

Random Array from 0,100
 [[100  95  31   0]
 [ 43  54  13  97]
 [ 86  74  29  98]
 [ 39  52   8  75]]
Sum : [268 275  81 270] 
Mean : [67.   68.75 20.25 67.5 ] 
Standard Deviation:  [26.50471656 17.42663192  9.93415824 40.04060439]
[[ True False False  True]
 [False  True False False]
 [ True  True False  True]
 [False  True  True False]]
New Array With Square Root of only Even Elements :
 [[10 95 31  0]
 [43  7 13 97]
 [ 9  8 29  9]
 [39  7  2 75]]


In [ ]:
# round 
A=np.random.random(size=(4,4)) * 100
#using with astype()
B=A.astype(np.int32)

#using with ro

[[80.70801856 88.59210933 56.32983602 22.03050347]
 [91.80367174 70.74500039 91.99250892 63.5616512 ]
 [ 6.83201581 35.66255583 25.06570024 78.29611374]
 [58.67656402 95.82755362 19.45535271 75.14183938]]
[[80 88 56 22]
 [91 70 91 63]
 [ 6 35 25 78]
 [58 95 19 75]]


# Indexing And Slicing 

In [ ]:
# Array Indexing
import numpy as np

#1D Array
a = np.array([10, 20, 30, 40])
print(a[0])     # 10
print(a[-1])    # 40

#2D Array :Matrix
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b[0, 1])  # 2 (row 0, column 1)


10
40
2


In [59]:
# 3D Array :Tensor
np.random.seed(1)
a3=np.random.randint(0,10,size=(2,2,2))
print("3D \n",a3)

# to print 9
print(a3[0,1,0])

# to print 7
print(a3[1,1,1])

# to print 1
print(a3[1,1,0])

3D 
 [[[5 8]
  [9 5]]

 [[0 0]
  [1 7]]]
9
7
1


In [63]:
# Array Slicing :Slicing means selecting a subsection of an array using the syntax:
"""
array[start:stop:step]
"""
# 1D : Similar to List and string 
a = np.array([10, 20, 30, 40, 50])
print(a)

print(a[1:4])   # [20 30 40]
print(a[::2])   
print(a[::-1])  # Reverse


[10 20 30 40 50]
[20 30 40]
[10 30 50]
[50 40 30 20 10]


In [117]:
# TO stop new random values
np.random.seed(0)
# 2D 

b = np.random.randint(0,10,size=(4,4))
print(b)
"""
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
 """


# Only 1st row 
print("1st Row")
print(b[0,:])      # (row 1, all columns)
# 3rd row 
print("3rd row")
print(b[2, :])     # (row 3, all columns)


# only 1st column
print("1st Column")
print(b[:,0])

# only 3rd column
print("3rd Column")
print(b[:,2])


print("Specific part :\n arr2D[row_start:row_stop, col_start:col_stop]")
"arr2D[row_start:row_stop, col_start:col_stop]"
print(b[2:4,1:3])

print(b[:,1:])

print(b[::3,::3])


print(b[::3,1::2])

print(b[1,::3])


print(b[1:3,1:])

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
1st Row
[5 0 3 3]
3rd row
[2 4 7 6]
1st Column
[5 7 2 8]
3rd Column
[3 3 7 1]
Specific part :
 arr2D[row_start:row_stop, col_start:col_stop]
[[4 7]
 [8 1]]
[[0 3 3]
 [9 3 5]
 [4 7 6]
 [8 1 6]]
[[5 3]
 [8 6]]
[[0 3]
 [8 6]]
[7 5]
[[9 3 5]
 [4 7 6]]


In [ ]:
# QUestion 
arr = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])
"""
Try to get:

1.Second row

2.Last column

3.Top-left 2x2 subarray

4.A diagonal """

print(arr)
#1
print(arr[1,:])

#2 
print(arr[:,2])

#3
print(arr[0:2,1:])

#4
"""
indices = np.arange(3)  # [0, 1, 2]
arr[indices, indices]   # → [arr[0,0], arr[1,1], arr[2,2]]
"""
print(arr[np.arange(3),np.arange(3)])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[40 50 60]
[30 60 90]
[[20 30]
 [50 60]]
[10 50 90]


In [130]:
# 3D Slicing:
a=np.arange(27).reshape(3,3,3)
print(a)
"""
arr3D[start_depth:end_depth, start_row:end_row, start_col:end_col]
"""
#1 print 2nd sub 2D array
print("1.\n",a[1])

#2 print last two sub 2D array
print("2.\n",a[1:,])

#3 print Alternate sub 2D arrays
print("3.\n",a[::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
1.
 [[ 9 10 11]
 [12 13 14]
 [15 16 17]]
2.
 [[[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
3.
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
#print 1st 2d array : 2nd row
print("4. \n",a[0,1])

#print 2nd 2d array:2nd column
print("5.\n",a[1,:,1])

#print 3nd 2d array:left bottom 2*2 array
print("6.\n",a[2,1:,1:])

#print 1st 2d array and 3rd 2d array :top left and right element
print("7.\n",a[::2,0,::2])

4. 
 [3 4 5]
5.
 [10 13 16]
6.
 [[22 23]
 [25 26]]
7.
 [[ 0  2]
 [18 20]]


In [143]:
#Iterting Numpy array
A1=np.arange(12)
A2=np.arange(12).reshape(4,3)
A3=np.arange(12).reshape(3,2,2)

In [ ]:
# 1d :print each element one by one

for i in A1:
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
#2D : print the each row one by one
for i in A2:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [ ]:
#3D :print the 2D array one by one
for i in A3:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[[ 8  9]
 [10 11]]


In [ ]:
# to print always Elements: WE use The nd.nditer() function
# it convert the n dimensional array to 1d and print the Elements one by one 
for i in np.nditer(A3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
# Transpose(): CHange the rows into columns and vice versa
# it does not change the original array just return the new array
print(A2)
print("Transpose\n",A2.transpose())

c=A2.transpose()
print(c)

d=np.transpose(A2)
print(d)

# simle method array.T
print(A2.T)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Transpose
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# ravel  : convert n dimensional array into 1 d
# it does not change the original array just return the new array
print(A3)
print("1D format\n",(A3.ravel()))

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
1D format
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


# Stacking

Stacking means joining two or more arrays along a new or existing axis.

Think of stacking like:

- Vertical stacking → stacking pages on top of each other

- Horizontal stacking → laying bricks side by side

- Depth stacking → stacking slices into layers



In [ ]:
"""
np.hstack()	      Stack horizontally (column-wise)
np.vstack()	      Stack vertically (row-wise)
np.dstack()	      Stack depth-wise (along 3rd axis)
np.stack()	      Stack along any axis
np.concatenate()	Join arrays along existing axis

"""

In [ ]:
a4=np.arange(0,12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

In [183]:
# Horizontal Stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [163]:
# verticle Stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [172]:
# depth Stacking : add one more dimensional
c=np.dstack((a4,a5))
print(c)


[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [181]:
# custom stacking : axis=0 -> verticle and axis=1 -> horizontal

"""
np.stack((a, b), axis=0):
Adds a new axis at position 0
"""
k=np.stack((a4,a5),axis=0)
print(k)


print("\n\n")
"""
np.stack((a, b), axis=1):
Adds a new axis at position 1
"""
m=np.stack((a4,a5),axis=1)
print(m)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]



[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


# Splitting:

Splitting means dividing one array into multiple sub-arrays along a specific axis.

Useful when you want to:

Split data into batches

Divide datasets into training/testing sets

Process parts of arrays independently



In [ ]:
"""
np.split()	Split evenly into parts (specify number of splits)
np.array_split()	Split into parts (can be uneven sizes)
np.hsplit()	Horizontal split (columns)
np.vsplit()	Vertical split (rows)
np.dsplit()	Depth-wise split (3D arrays)
"""

''

In [186]:
import numpy as np

arr = np.array([
    [10, 20, 30, 40, 50, 60],
    [70, 80, 90, 100, 110, 120]
])
# shape = (2, 6)
print(arr.shape)

(2, 6)


 In NumPy:

__axis=0 means  rows are affected (operate down the columns)__

__axis=1 means  columns are affected (operate across the rows)__



In [199]:
# np.split() → Split evenly
np.split(arr, 3,axis=1)


[array([[10, 20],
        [70, 80]]),
 array([[ 30,  40],
        [ 90, 100]]),
 array([[ 50,  60],
        [110, 120]])]

In [206]:
#  np.array_split() → Allows uneven splits

np.array_split(arr, 4, axis=0)


[array([[10, 20, 30, 40, 50, 60]]),
 array([[ 70,  80,  90, 100, 110, 120]]),
 array([], shape=(0, 6), dtype=int64),
 array([], shape=(0, 6), dtype=int64)]

In [214]:
#np.hsplit() → Split horizontally (columns)
np.hsplit(arr, 6)


[array([[10],
        [70]]),
 array([[20],
        [80]]),
 array([[30],
        [90]]),
 array([[ 40],
        [100]]),
 array([[ 50],
        [110]]),
 array([[ 60],
        [120]])]

In [209]:
#   np.vsplit() → Split vertically (rows)
np.vsplit(arr, 2)


[array([[10, 20, 30, 40, 50, 60]]), array([[ 70,  80,  90, 100, 110, 120]])]

In [ ]:
# np.dsplit() → Split along depth 
arr3D = np.arange(24).reshape(2, 3, 4)

np.dsplit(arr3D, 2)  # Split along 3rd axis (depth)


[array([[[ 0,  1],
         [ 4,  5],
         [ 8,  9]],
 
        [[12, 13],
         [16, 17],
         [20, 21]]]),
 array([[[ 2,  3],
         [ 6,  7],
         [10, 11]],
 
        [[14, 15],
         [18, 19],
         [22, 23]]])]