__DAY 4__

In [2]:
import numpy as np

__SPeed Comparision : (python list and numpy_array)__

In [3]:
# speed of List :
A=[i for i in range(0,10000000)]
B=[i for i in range(10000000,20000000)]

In [4]:
import time 
start=time.monotonic()
c=[]
for i in range(len(A)):
    c.append(A[i]+B[i])

end=time.monotonic()
print("Time Taken ",end-start)

Time Taken  11.827651900001001


In [5]:
#Numpy Speed
numpyA=np.arange(0,10000000)
numpyB=np.arange(10000000,20000000)


In [6]:
start=time.monotonic()

numpyc=numpyA+numpyB

end=time.monotonic()
print("Time Taken ",end-start)

Time Taken  0.08554999999978463


__Numpy Is Approximately 10-50 times Faster than Python Lists__

__Why__
- NumPy arrays use C-style arrays underneath.

- - This means:

  - Data is stored in contiguous memory blocks.

  - All elements are of the same data type, enabling fast access and arithmetic using compiled C loops.
  - Python List: stores references to objects
   - NumPy Array: stores raw values directly in memory
- No Reference Overhead
  - Python lists store pointers (references) to actual objects.

  - Every time you access an element in a list, Python follows the reference to get the value.

  - NumPy arrays store the actual values in memory, not references.NumPy avoids this extra step = faster access.NumPy arrays are fixed-size.

- You can’t insert or delete elements directly.

- Homogenous data in Numpy arrays .

- convenient way to code with larger data sets

__Memory comparision : (python list and numpy_array)__

In [7]:
#List Size 
import sys
A=[i for i in range(0,10000000)]
size=sys.getsizeof(A)/(1024*8)
print("Size :",size,"Mb")

Size : 10875.8740234375 Mb


In [8]:
#Numpy array Size 
import sys
A=np.arange(10000000)
size=sys.getsizeof(A)/(1024*8)
print("Size :",size,"Mb")

# we can Observe both are almost same memory

Size : 9765.638671875 Mb


In [9]:
# using lower Precision numbers like int8,int16 ,int32 
# to reduce the size 
# for example storing the month (1-12) we can use int8 rather than int64
# that highly reduce the size
A=np.arange(10000000,dtype=np.int16)
size=sys.getsizeof(A)/(1024*8)
print("Size :",size,"Mb")

Size : 2441.419921875 Mb


# Advance Indexing (Fancy Indexing,Boolean Indexing)

In [10]:
#simple Indexing
a=np.arange(12).reshape(4,3)
print(a)

# indexing
print(a[1,1])

# slicing
print(a[1:3,1:])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
4
[[4 5]
 [7 8]]


__Fancy Indexing__

In [11]:
"""Fancy indexing means:
 indexing an array using a list or array of indices,
   rather than a single index or a slice.

It gives you more control over which elements to extract, reorder, or modify.
"""

'Fancy indexing means:\n indexing an array using a list or array of indices,\n   rather than a single index or a slice.\n\nIt gives you more control over which elements to extract, reorder, or modify.\n'

In [12]:

# what if someone says you to get only the 1st row ,3rd row and 4th row
# here we cannot find any pattern for slicing so use the Fancy Indexing
# we cannot do this with slicing and indexing directly

#so pass the directly  index_list  of what you want 

arr = np.array([10, 20, 30, 40, 50])

# Access elements at index 0, 3, and 4
indices = [0, 3, 4]
print(arr[indices])  # Output: [10 30 50]


[10 40 50]


In [13]:
# Repeat and reorder elements
print(arr[[4, 4, 0, 1]])  # Output: [50 50 10 20]

[50 50 10 20]


In [14]:
# Fancy Indexing in 2D Arrays
"""SyntAx:
arr2d[row_indices, col_indices]"""

a=np.arange(0,24).reshape(6,4)
print("array\n",a)

# access the 1st,2nd,5th,3rd,2nd row in same order  and all columns 
rows=[0,1,4,2,1]
print("\n1st,2nd,5th,3rd,2nd \n",a[rows])

# access all rows and columns in order 1st,3rd,2nd
columns=[0,2,1]
print("\nall rows -> 1st,3rd,2nd columns \n",a[:,columns])

array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

1st,2nd,5th,3rd,2nd 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]]

all rows -> 1st,3rd,2nd columns 
 [[ 0  2  1]
 [ 4  6  5]
 [ 8 10  9]
 [12 14 13]
 [16 18 17]
 [20 22 21]]


In [15]:
# Modifying Values with Fancy Indexing
# change the 1st row,2nd row,5th row =0
c=a.copy()
print(c)
rows=[0,1,4]
c[rows]=0

print("After changing to 0\n",c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
After changing to 0
 [[ 0  0  0  0]
 [ 0  0  0  0]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  0  0  0]
 [20 21 22 23]]


__Boolean Indexing__

In [16]:
""" Boolean Indexing lets you filter NumPy arrays
  using boolean values (True / False).
"""

' Boolean Indexing lets you filter NumPy arrays\n  using boolean values (True / False).\n'

In [17]:

# question: Create the Numpy array that contains elements >30 from given array
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Get elements greater than 30
mask = arr > 30
print("Boolean mask:", mask)         # [False False False  True  True]
print("Filtered values:", arr[mask]) # [40 50]


Boolean mask: [False False False  True  True]
Filtered values: [40 50]


In [18]:
"""
Q.
1.create the Numpy array of (6,4) random numbers from 1-100

2.create the Numpy array Such that elements >50 from Above Array.

3. Create the Numpy arrry such that elements are Even from above array

4. Create the Numpy arrry such that elements are ( Even and >50 ) from above array
 """

#1..
Array=np.random.randint(1,100,size=(6,4))
print(Array)

[[97 12  5 13]
 [33 21 25 22]
 [89 69 49 99]
 [53 42 90 29]
 [44 13 80 14]
 [94 14 45 63]]


In [19]:
#2..
# Getting the Boolean Array
mask=Array > 50 
print(mask)

#using this Boolean Array As mask to get the COndtion True Elements only
TrueValueElements=a[mask]
print(TrueValueElements)

[[ True False False False]
 [False False False False]
 [ True  True False  True]
 [ True False  True False]
 [False False  True False]
 [ True False False  True]]
[ 0  8  9 11 12 14 18 20 23]


In [20]:
#3..
#boolean format
mask=(Array%2==0)
print(mask)
#print the Condition True ELements(Even Numbers)
print(Array[mask])


[[False  True False False]
 [False False False  True]
 [False False False False]
 [False  True  True False]
 [ True False  True  True]
 [ True  True False False]]
[12 22 42 90 44 80 14 94 14]


___Understanding The( and ) And (&) Difference :__


--> (&) — Bitwise AND (Binary logic)

Used with integers or arrays (like NumPy arrays).Performs a bitwise AND operation on corresponding bits.

--> Using (and) with NumPy arrays raises an error.

__Why?__ 
--> When We use (and) Python expects a single boolean value on each side, like:
(True and False  # Works)

but when we use 


a = np.array([True, False, True])

b = np.array([False, False, True])

a and b  #  Error!

Python doesn’t know what to do here, because:

a and b are arrays, not simple True or False.

Python tries to convert the arrays to a single boolean, like bool(a), but...

When you do bool(a) on a NumPy array with more than one element, NumPy raises this error:
"""

In [21]:
#4..
"""Use & , | , and ~  with parentheses around conditions"""
mask=((Array>50) & (Array%2==0))
print(mask)

print(Array[mask])

[[False False False False]
 [False False False False]
 [False False False False]
 [False False  True False]
 [False False  True False]
 [ True False False False]]
[90 80 94]


__BroadCasting__

The Term Broadcasting Describes How Numpy treats Arrays with Different Shapes During Arithmetic Opeations.

The smaller Array is "broadcast" across the larger array so that they can have compatible Shapes

__Broadcasting is the method NumPy uses to perform operations on arrays of different shapes as if they had the same shape, without actually copying the data.__

__It’s like “stretching” the smaller array to match the bigger one — automatically and efficiently.__ 



In [33]:
# same Shapes Operations:
a=np.arange(6).reshape(2,3)
b=np.arange(6).reshape(2,3)

a+b

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [25]:
# Different Shapes Operations:
a=np.arange(6).reshape(2,3)
print("a=\n",a)
b=np.arange(3).reshape(1,3)
print("b=\n",b)

a+b

a=
 [[0 1 2]
 [3 4 5]]
b=
 [[0 1 2]]


array([[0, 2, 4],
       [3, 5, 7]])

#### Broadcasting Rules

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

**2. Make each dimension of the two arrays the same size.**<br>
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In [34]:
# more Examples
a=np.arange(12).reshape(4,3)    #-> (4,3)
print("a=\n",a)
b=np.arange(3).reshape(3)       #-> (3,)
print("b=\n",b)
"""
How broadcasting happens:

a.shape = (4, 3)
b.shape = (3,)

Step 1:
Align shapes from the right:
a -> (4, 3)
b ->     (3)

Step 2:
Match dimensions:
- b has fewer dimensions → add a new dimension at the beginning of size 1
  b becomes (1, 3)

Step 3:
Broadcast:
- a is (4, 3)
- b is (1, 3)
→ NumPy stretches bs first dimension from 1 to 4

Final broadcasted b:
[[0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2]]  # Shape: (4, 3)

Now shapes match → element-wise addition works
"""


a+b

a=
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
b=
 [0 1 2]


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [ ]:
a=np.arange(12).reshape(4,3)    #->(4,3)
print("a=\n",a)
b=np.arange(4).reshape(4,1)     #->(4,1)
print("b=\n",b)

"""
a.shape = (4, 3)
b.shape = (4, 1)

Step 1: Align shapes from the right
a → (4, 3)
b → (4, 1)

->(Same Dimension)
Step 2: Compare each dimension
- First dimension: 4 vs 4 →  same
- Second dimension: 3 vs 1 →  1 can be stretched

Step 3: Stretch b to match shape (4, 3)
b becomes:
[[0, 0, 0],
 [1, 1, 1],
 [2, 2, 2],
 [3, 3, 3]]

Now both a and b are (4, 3) → Element-wise addition happens!
"""

a+b

a=
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
b=
 [[0]
 [1]
 [2]
 [3]]


array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [42]:
a=np.arange(12).reshape(3,4)    #->(3,4)
print("a=\n",a)
b=np.arange(3).reshape(3)     #->(3,)
print("b=\n",b)
"""
a.shape = (3, 4)
b.shape = (3,)

Step 1: Align shapes from the right
a → (3,4)
b → (, 3)

Step 2: Match dimensions:
- b has fewer dimensions → add a new dimension at the beginning of size 1
  b becomes (1, 3)

step3:
Compare each dimension
- First dimension: 3 vs 1 →  1 can be stretched to 3
- Second dimension: 3 vs 3→  here dimension not matches and not 1 (So no Streching)

# here we can see that 2nd dimension not matches and not equal to 1
# Broadcasting only works if:
1..Dimensions Matches, or
2...One of them is 1 (so it can be stretched)
..

Error::
"""
a+b

a=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b=
 [0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [43]:
a=np.arange(3).reshape(1,3)    #->(1,3)
print("a=\n",a)
b=np.arange(4).reshape(4,1)     #->(4,1)
print("b=\n",b)

"""
a.shape = (1, 3)
b.shape = (4, 1)

Step 1: Align shapes from the right
a → (1, 3)
b → (4, 1)
->(Same Dimension)
Step 2: Compare each dimension
- First dimension: 1 vs4  →  1 can be stretched to 4
- Second dimension: 3 vs 1 →  1 can be stretched to 3

Step 3: Stretch b to match shape (4, 3)
a becomes :
[[0,1,2],
[0,1,2],
[0,1,2],
[0,1,2]]


b becomes :
[[0,0,0],
[1,1,1],
[2,2,2],
[3,3,3]]
Now both a and b are (4, 3) → Element-wise addition happens!
"""
a+b

a=
 [[0 1 2]]
b=
 [[0]
 [1]
 [2]
 [3]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [50]:
a=np.array([1])
b=np.arange(4).reshape(2,2)
print("a=\n",a)
print("b=\n",b)

"""
How broadcasting happens:

a.shape = (1)
b.shape = (2,2)

Step 1:
Align shapes from the right:
a -> ( ,1)
b -> (2,2)

Step 2:
Match dimensions:
- 1 has fewer dimensions → add a new dimension at the beginning of size 1
  1 becomes (1, 1)

Step 3:
Broadcast:
- a is (1, 1)
- b is (2, 2)
→ NumPy stretches a first dimension from 1 to 2 
a -> [1,1]
→ NumPy stretches a Second dimension from 1 to 2 
a->[[1,1],
    [1,1]]
Final broadcasted a:
 a->[[1,1],
    [1,1]]# Shape: (2, 2)

Now shapes match → element-wise addition works
"""

a+b


a=
 [1]
b=
 [[0 1]
 [2 3]]


array([[1, 2],
       [3, 4]])

In [ ]:
a=np.arange(16).reshape(4,4)
b=np.arange(4).reshape(2,2)
print("a=\n",a)
print("b=\n",b)
"""
How broadcasting happens:

a.shape = (4,4)
b.shape = (2,2)

Step 1:
Align shapes from the right:
a -> ( 4,4)
b -> (2,2)

Step 2:
Match dimensions:
--> Same Dimensions 2D

Step 3:
Broadcast:
- a is (4, 4)
- b is (2, 2)
b -> does not have 1 in size

# here we can see that both  dimensions of (b not matches with a) and (not equal to 1 )
# Broadcasting only works if:
1..Dimensions Matches, or
2...One of them is 1 (so it can be stretched)
..

Error
"""

a+b

a=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
b=
 [[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

[__DAY 5__](./NumpyDay5.ipynb)