__DAY 1__

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

 Difference Between the Numpy array vs Python Sequences(list,tuple,sets)

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

__Important Questions :__


1.What is NumPy?

2.Why use NumPy instead of lists?

3.How to install and import it

4.Creating NumPy arrays

5.Basic array operations

 1. What is NumPy?
NumPy (Numerical Python) is a library for fast, efficient operations on large arrays and matrices of numeric data.

 2. Why NumPy over Python Lists?
- Faster execution

- Uses less memory

- Has many built-in mathematical operations

- Supports broadcasting (element-wise operations without loops)

 3. Installation & Import

pip install numpy

import numpy as np


 4. Creating Numpy Arrays

In [5]:
#importing the numpy 
import numpy as np

# 1D array:Vector
a = np.array([1, 2, 3])
print(a)
print(type(a))


# 2D array:Matrix   
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(type(b))

# 3D Array :Tensor
c=np.array([[[1,2],[2,3]],[[2,3],[24,4]]])
print(c)
print(type(c))


[1 2 3]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[[ 1  2]
  [ 2  3]]

 [[ 2  3]
  [24  4]]]
<class 'numpy.ndarray'>


In [ ]:
#Some Important Methods and Attributes :|
                                        

In [ ]:
# Our Own Datatype Numpy array
# dtype=type
# float Array
import numpy as n
float_array=n.array([1,2,3] , dtype=float)
print(float_array)

# bool type
bool_array=n.array([1,2,3],dtype=bool)
print(bool_array)

[1. 2. 3.]
[ True  True  True]


In [ ]:
# np.arange(start,end,step)::Creates an array with regularly spaced values (like Python's range() but returns a NumPy array).
# similar to range(start,end,step)
# it return the Numpy array
print("Numpy Array of 0,10",n.arange(0,11))
b=print("Numpy Array of even Numbers 0,20",n.arange(0,21,2))


Numpy Array of 0,10 [ 0  1  2  3  4  5  6  7  8  9 10]
Numpy Array of even Numbers 0,20 [ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
# check the shape of our array 
# np.shape
x=np.array([[1,2,3],[2,3,4]])
print(x)
Shape=x.shape
print(Shape)   # (2,3) rows=2 and colums =3

[[1 2 3]
 [2 3 4]]
(2, 3)


In [4]:
#Changes the shape/structure of an array without changing its data.4
# reshape(array , (newshape))
# reshape(newshape)

import numpy as np
# reshape(array , (newshape))
myarray=np.arange(0,10)
print(myarray)
print(myarray.shape)
x=np.reshape(myarray,(5,2))
print(x)

# reshape(newshape)
Numpy_array=np.arange(0,10)
newarray=Numpy_array.reshape(2,5)
print(newarray)

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:

# Zeros, Ones, and Random: USED To Initialize the Things
zeros = np.zeros((3, 3))
ones = np.ones((3, 3))
randoms = np.random.random((3, 3))

print("\n\nZeroes Array (3*3)\n",zeros)
print("\nZeroes Array (3*3)\n",ones)
print("\nRandom Number Array (3*3)\n",randoms)




Zeroes Array (3*3)
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Zeroes Array (3*3)
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Random Number Array (3*3)
 [[0.43064127 0.74255023 0.76627421]
 [0.75876206 0.33718616 0.02322152]
 [0.35826562 0.42636613 0.58116035]]


In [24]:
# np.linspace(start, stop, num=50, endpoint=True, retstep=False)
# Returns an array of (evenly spaced values) over a specified interval.

"""
start: The starting value of the sequence.

stop: The end value of the sequence.

num: Number of points (default is 50).

endpoint: If True (default), include stop; otherwise, dont take  it.

retstep: If True, returns (array, step size).(by default it is false)
"""

# using the np.linspace()
x=np.linspace(-10,10,10)
print(x)

# using it with endpoint 
x=np.linspace(-10,10,10,endpoint=False,dtype=int)
print(x)

#using the retstep
x,step=np.linspace(-10,10,10,retstep=True)
print(x)
print("step ",step)

"""
Real Use Cases:
Creating smooth X-axis data for plotting curves

Generating inputs for simulation or equally spaced intervals

Useful in data normalization, interpolation, or binning

"""


[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]
[-10  -8  -6  -4  -2   0   2   4   6   8]
[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]
step  2.2222222222222223


'\nReal Use Cases:\nCreating smooth X-axis data for plotting curves\n\nGenerating inputs for simulation or equally spaced intervals\n\nUseful in data normalization, interpolation, or binning\n\n'

In [58]:
# np.identity(n, dtype=None)
#n: Number of rows and columns (since it’s square).

#dtype: Data type (optional), like float, int, etc.
print(np.identity(3,dtype=int))


# np.eye()
# np.identity(n) only creates square matrices
# np.eye(n, m) lets you create non-square matrices and set diagonal offset(n,m) rows,columns
print(np.eye(3,4))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


# Numpy Attributes

In [ ]:
import numpy as np
#Example Arrays
A1=np.arange(10)
A2=np.arange(12,dtype=float).reshape(3,4)
A3=np.arange(8,dtype=np.int32).reshape(2,2,2)
print(A1,'\n\n',A2,"\n\n",A3)

[0 1 2 3 4 5 6 7 8 9] 

 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 

 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [49]:
# ndim Attribute : Dimension of the Array 
print(A1.ndim)
print(A2.ndim)
print(A3.ndim)

1
2
3


In [50]:
# shape : To get the shape of the np.array
# we have discussed this already above
print(A1.shape)
print(A2.shape)
print(A3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [51]:
# size :provides the Number of elements of the array
print(A1.size)
print(A2.size)
print(A3.size)

10
12
8


In [55]:
# itemsize : Gives how much memory the each element of numpy array takes in Memory 
# in bytes
print(A1.itemsize)
print(A2.itemsize)
print(A3.itemsize)

8
8
4


In [56]:
# dtype : gives the datatype of the items of Numpy array
print(A1.dtype)
print(A2.dtype)
print(A3.dtype)

int64
float64
int32


# Changing Datatypes Of Numpy Array: type conversion.

In [ ]:
# astype():Converts (or casts) the data type of a NumPy array to a different one.
k,step=np.linspace(0,10,5,retstep=True,endpoint=False)
print(k,"Step :",step)
print(k.dtype)
print(k.itemsize,"kb")

# to reduce size we can use the astype() to change its type to int32
# Note: astype() returns a copy, not an in-place change. We have to assign it to some variable

m=k.astype(np.int32)
print(k)
print(k.itemsize)
print(m)
print(m.itemsize)

[0. 2. 4. 6. 8.] Step : 2.0
float64
8 kb
[0. 2. 4. 6. 8.]
8
<class 'numpy.ndarray'>
4


[__Day 2__](./NumpyDay2.ipynb)