__Day 5__

__Core Mathematical functions__ :

__Used In Ml and DL__ 

1. __Sigmoid Function__

The Sigmoid function maps any real number to a value between 0 and 1.

Formula:
      
$$\Large \sigma( x) = \frac{1}{1 + e^{-x}}$$

It "squashes" input values into a smooth curve.

Often used to represent probability (e.g., output of a binary classifier).



In [2]:
"""
Sigmoid Curve Shape
As x → -∞, sigmoid → 0

As x → +∞, sigmoid → 1

At x = 0, sigmoid = 0.5
"""

'\nSigmoid Curve Shape\nAs x → -∞, sigmoid → 0\n\nAs x → +∞, sigmoid → 1\n\nAt x = 0, sigmoid = 0.5\n'

It has an S-shaped curve, like this:

          1 |
            |                       _______
            |                    /
            |                 /
            |              /
            |           /
          0 |_________/_________________
            -6      0         +6      x


__SIGMOID With Numpy__

In [3]:
# Sigmoid Function With Numpy:
import numpy as np
def Sigmoid(numpy_array):
    Solution=1/(1+np.exp(-(numpy_array)))
    return Solution

#1 Example
A=np.arange(100)
sigmoid_array=Sigmoid(A)
print(A)
print("\nSigmoid Array\n ",sigmoid_array)

#2 example
print("\nSigmoid Array\n",Sigmoid(np.array([-2, 0, 2])))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Sigmoid Array
  [0.5        0.73105858 0.88079708 0.95257413 0.98201379 0.99330715
 0.99752738 0.99908895 0.99966465 0.99987661 0.9999546  0.9999833
 0.99999386 0.99999774 0.99999917 0.99999969 0.99999989 0.99999996
 0.99999998 0.99999999 1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.  

__Sigmoid USed IN ML in__
  - Logistic Regression
  - Neural Networks
  - Binary Classification

-----------------------

2. __MSE (Mean Squared Error )__

MSE measures the average squared difference between the predicted values and actual (true) values.

- linear Regression

$$
\text{MSE} = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2
$$

yi= actual/true value

𝑦^𝑖 = predicted value

n = number of samples

In [28]:
# MSE With Numpy
np.random.seed(1)
Actual=np.random.randint(1,50,size=20)
Predicted=np.random.randint(1,50,size=20)
print("Actual_Data=\n",Actual)
print("Predicted_Data\n",Predicted)

Actual_Data=
 [38 44 13  9 10 12  6 16  1 17  2 13  8 46  7 26 21 38 19 21]
Predicted_Data
 [12 43 29 30 15  5 24 24 42 31 33 23 14 42 10  8 23  2  1 18]


In [30]:
# mse Function numpy based
def MSE(actual,Predict):
    return np.mean((actual-Predict)**2)
    
print("MEan Squared Error",MSE(Actual,Predicted))


MEan Squared Error 339.6


In [36]:
# how we get the things
print(Actual-Predicted,"\n\n",
np.square(Actual-Predicted),"\n\n",
np.mean(np.square(Actual-Predicted)))

[ 26   1 -16 -21  -5   7 -18  -8 -41 -14 -31 -10  -6   4  -3  18  -2  36
  18   3] 

 [ 676    1  256  441   25   49  324   64 1681  196  961  100   36   16
    9  324    4 1296  324    9] 

 339.6


---------------------------

__Why Use Cross-Entropy? In ML__

1.Binary Classification	          ->Binary Cross-Entropy

2.Multi-Class (One label)	      ->Categorical Cross-Entropy

3.Multi-Label	                  ->Binary Cross-Entropy (per label)__

1. __Binary --- Cross-ENtopy Loss (Log Loss)__


Cross-entropy loss also known as log loss is a metric used in machine learning to measure the performance of a classification model..
Cross-Entropy Loss (a.k.a. Log Loss) measures the difference between actual labels and predicted probabilities. It’s used when:

You’re predicting class probabilities

Typically applied in binary and multi-class classification

- logical Regression

__Formula__
$$
\text{Binary Cross-Entropy (BCE)} = - \frac{1}{n} \sum_{i=1}^{n} \left[ y_i \cdot \log(\hat{y}_i) + (1 - y_i) \cdot \log(1 - \hat{y}_i) \right]
$$
Where:

𝑛 = number of samples

𝑦𝑖 ∈{0 ,1} = true label

𝑦^𝑖∈(0,1): predicted probability (from sigmoid)


In [38]:
"""
np.clip(array,min_value,max_value)
It restricts all values in the array to be between min_val and max_val."""
import numpy as np

arr = np.array([0.0, 0.5, 1.0])
clipped = np.clip(arr, 1e-9, 1 - 1e-9)

print(clipped)  


[1.00000000e-09 5.00000000e-01 9.99999999e-01]


In [39]:
import numpy as np

def binary_cross_entropy(true, pred):
    # Avoid log(0) by clipping values to avoid the 0 in our predicted we use the clip
    pred = np.clip(pred, 1e-9, 1 - 1e-9)
    return -np.mean(true * np.log(pred) + (1 - true) * np.log(1 - pred))

# Example
true = np.array([1, 0, 1])
pred = np.array([0.9, 0.1, 0.8])

print(binary_cross_entropy(true, pred))  # Low loss = good prediction


0.14462152754328741


----------

2. Categorical Cross-Entropy Loss (Multi-Class with Softmax)

$$
\text{Categorical Cross-Entropy (CCE)} = - \frac{1}{n} \sum_{i=1}^{n} \sum_{c=1}^{C} y_{i,c} \cdot \log(\hat{y}_{i,c})
$$


In [40]:
import numpy as np

def categorical_cross_entropy(y_true, y_pred):
    # Clip predicted values to avoid log(0)
    y_pred = np.clip(y_pred, 1e-9, 1 - 1e-9)
    return -np.mean(np.sum(y_true * np.log(y_pred), axis=1))

# Example: 3 samples, 3 classes
y_true = np.array([
    [1, 0, 0],  # Class 0
    [0, 1, 0],  # Class 1
    [0, 0, 1]   # Class 2
])

y_pred = np.array([
    [0.9, 0.05, 0.05],   # Correct (high confidence)
    [0.1, 0.8, 0.1],     # Correct
    [0.2, 0.2, 0.6]      # Correct
])

loss = categorical_cross_entropy(y_true, y_pred)
print("CCE Loss:", loss)


CCE Loss: 0.2797765635793423


[Day6](./NumpyDay6.ipynb)