###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [117]:
# code here
import numpy as np
arr=np.array([[92, 90, 74],
              [ 6, 63, 93],
              [15, 93, 96],
              [70, 60, 48]])

#1
np.sort(arr)

array([[74, 90, 92],
       [ 6, 63, 93],
       [15, 93, 96],
       [48, 60, 70]])

In [118]:
#2
"""sort by a Specific Row,column
If you want to sort columns of the array based on the values in a specific row:
np.argsort() givees the index of sorted array
"""
print(np.argsort(arr))

# first get indices of what you want to sort
#it gives the indices of the rows that would sort the array based on column 2.”
sortedindex=np.argsort(arr[: , 1])  # 2nd column sorted index
print("Sorted Index\n",sortedindex)


# use those index to sort each column
sorted_arr=arr[sortedindex]
print("sorted INdex\n",sorted_arr)

[[2 1 0]
 [0 1 2]
 [0 1 2]
 [2 1 0]]
Sorted Index
 [3 1 0 2]
sorted INdex
 [[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]


In [119]:
#3 
x=np.sort(arr,axis=1)
print(x)

# reverse Order
x=x[: , ::-1]
print(x)

[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]
[[92 90 74]
 [93 63  6]
 [96 93 15]
 [70 60 48]]


In [120]:
#4
np.sort(arr,axis=None).reshape(arr.shape)

array([[ 6, 15, 48],
       [60, 63, 70],
       [74, 90, 92],
       [93, 93, 96]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [121]:
# code here
import numpy as np
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]
data=np.array(marks)

extra_subject = [41, 87, 72, 36, 92]
extra=np.array(extra_subject )
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]

rec2 = [92, 71, 52, 61, 53]


In [122]:
# 1
extra=np.expand_dims(extra,axis=1)
newdata=np.hstack((data,extra))
print(newdata)
print(data)

[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]
[[13 10  9 33]
 [63 46 90 42]
 [39 76 13 29]
 [82  9 29 78]
 [67 61 59 36]]


In [123]:
#2 
stu1=np.array(rec1)
stu2=np.array(rec2)
newdata=np.vstack((newdata,stu1,stu2))
print(newdata)


[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]


In [124]:
# 3
Row_sum=np.sum(newdata,axis=1)
print(Row_sum)
Row_sum=np.expand_dims(Row_sum,axis=1)
print(Row_sum)

print("\n sum added :")
newdata=np.append(newdata,Row_sum,axis=1)
print(newdata)

[106 328 229 234 315 442 329]
[[106]
 [328]
 [229]
 [234]
 [315]
 [442]
 [329]]

 sum added :
[[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


In [125]:
# 4 sort the array according to last row 
# In Descending order

print(newdata)
print(newdata.shape)
# getting the sorted row index
last_column_sortedIndex=np.argsort(newdata,axis=0)[:,-1]
print(last_column_sortedIndex)
# using those index for sorting
newdata=newdata[last_column_sortedIndex]
print(newdata)

# now convert it to reverse order
newdata=newdata[::-1]


[[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]
(7, 6)
[0 2 3 4 1 6 5]
[[ 13  10   9  33  41 106]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 63  46  90  42  87 328]
 [ 92  71  52  61  53 329]
 [ 77  83  98  95  89 442]]


In [134]:
print(newdata)

[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]
 [ 63  46  90  42  87 328]
 [ 67  61  59  36  92 315]
 [ 82   9  29  78  36 234]
 [ 39  76  13  29  72 229]
 [ 13  10   9  33  41 106]]


In [135]:
# 3 Toppers 
print(newdata[0:3,:])

[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]
 [ 63  46  90  42  87 328]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [140]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
np.unique(arr,axis=0)


array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

In [139]:
np.unique(arr,axis=1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [141]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

np.flip(arr,axis=None)

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [ ]:
# code here
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])

# simple Boolean Mask TO get > 6
X = 6
Mask=arr > X
print(Mask)

# to get Indices OF Elements
print(np.where(arr>6 )[0])



[[False False False False False]
 [ True False  True False False]
 [False False False False False]
 [ True  True False False False]]
[1 1 3 3]


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [157]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(4,7)
arr3 = np.arange(7,10)

GroupArray=np.array([[arr1],[arr2],[arr3]])
print(GroupArray)

[[[0 1 2]]

 [[4 5 6]]

 [[7 8 9]]]


In [158]:
# code here
GroupArray.flatten()

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [160]:
np.ravel(GroupArray)

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [173]:
# code here
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
print(arr)
print(arr.shape)
min=np.min(arr)
min_index=np.argmin(arr)
max=np.max(arr)
max_index=np.argmax(arr)
print("Minimun :",min,"  At Index ",min_index,"\nMaximum:",max,"  At Index ",max_index)

# to remove use delete 
arr=np.delete(arr,[min_index,max_index])
#it chnages the shape of array to flattend 1d
print(arr.shape)
# getting shape back 
arr= np.reshape(arr,(1,arr.size))
print(arr)

[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
  173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
  771 270 308 231 952 514 699 702 433 900 373 318 998 265 503 320 230 324
  922 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930
  325 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528
  395 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859
  618 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748
  291 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207
  883 588]]
(1, 200)
Minimun : 103   At Index  66 
Maximum: 998   At Index  102
(198,)
[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [ ]:
# code here
np.random.seed(8)
A=np.random.randint(100,700,size=100)
print(A,"\n")

Clipped_version=np.clip(A,100,200)
print("Clipped\n [100-200]",Clipped_version)

sorted=np.sort(Clipped_version)
print("Sorted:\n",sorted)

# it gives the full array of cummulative sum
cummulative_sum=np.cumsum(sorted)
print("Cummulative_sum\n",cummulative_sum)

[551 440 461 233 236 460 148 185 215 558 369 161 243 449 454 415 630 370
 202 449 540 663 270 510 422 109 481 594 181 576 447 591 675 698 131 120
 633 128 659 494 102 522 299 648 223 476 317 393 463 550 566 650 410 523
 146 451 260 107 482 493 526 119 404 628 212 306 218 205 348 198 315 326
 106 512 583 175 367 274 320 556 573 247 670 481 475 480 655 627 128 269
 244 686 261 593 554 619 518 250 576 441] 

Clipped
 [100-200] [200 200 200 200 200 200 148 185 200 200 200 161 200 200 200 200 200 200
 200 200 200 200 200 200 200 109 200 200 181 200 200 200 200 200 131 120
 200 128 200 200 102 200 200 200 200 200 200 200 200 200 200 200 200 200
 146 200 200 107 200 200 200 119 200 200 200 200 200 200 200 198 200 200
 106 200 200 175 200 200 200 200 200 200 200 200 200 200 200 200 128 200
 200 200 200 200 200 200 200 200 200 200]
Sorted:
 [102 106 107 109 119 120 128 128 131 146 148 161 175 181 185 198 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 2

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [205]:


np.random.seed(6)
arr = np.random.random(size=15)

# Round to 3 decimal places
arr = np.round(arr, 3)
print("Rounded array:", arr)

# Check 0th percentile == min
print("0th percentile == min:", np.percentile(arr, 0) == np.min(arr))

# Check 100th percentile == max
print("100th percentile == max:", np.percentile(arr, 100) == np.max(arr))

# Difference between 51st and 50th percentiles
diff = np.percentile(arr, 51) - np.percentile(arr, 50)
print("51st - 50th percentile =", diff)


Rounded array: [0.893 0.332 0.821 0.042 0.108 0.595 0.53  0.419 0.335 0.623 0.438 0.736
 0.518 0.579 0.645]
0th percentile == min: True
100th percentile == max: True
51st - 50th percentile = 0.006859999999999977
